version: '3'

services:
  flume:
    hostname: flume
    build: ./flume
    ports:
      - "1234:1234"
    depends_on:
      - kafka

  flume_second_agent:
    hostname: flume_second_agent
    build: ./flume_second_agent
    depends_on:
      - kafka

  kafka:
    hostname: kafka
    build: ./kafka
    ports:
      - "2181:2181"
      - "9092:9092"